spring:
  kafka:
    #bootstrap-servers:
    #  - 192.168.0.4:9092
    producer:
      bootstrap-servers: localhost:9092
      batch-size: 10
      retries: 1
      acks: 1
      # producer bootstrap servers? ?? ???? ??
      # bootstrap-servers: 3.34.97.97:9092
      # ???? ?? ?, key/value? ???
      # JSON ???? ?? ???? JsonDeserializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    topic:
      test: test

    consumer:
      # consumer bootstrap servers? ?? ???? ??
      # bootstrap-servers: 192.168.0.4:9092
      # ?? ??? Consumer Group Id
      group-id: testgroup
      # Kafka ??? ?? offset? ???, ??? ?? offset? ? ?? ???? ?? ?? ??? ??? ??
      # latest: ?? ??? ??? ???? offeset reset
      # earliest: ?? ??? ???? offeset reset
      # none: offset ??? ??? Exception ??
      auto-offset-reset: earliest
      # ???? ??? ?, key/value? ????
      # JSON ???? ??? ???? JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer